// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantePOS.Infrastructure.Data;

#nullable disable

namespace RestaurantePOS.Infrastructure.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    partial class RestauranteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.CategoriaPlato", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CategoriaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK_CategoriasPlato_CategoriaId");

                    b.ToTable("CategoriasPlato", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.DetalleOrden", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DetalleId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.Property<string>("EstadoPreparacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EstadoPreparacion");

                    b.Property<string>("ObservacionesCocina")
                        .HasColumnType("text")
                        .HasColumnName("ObservacionesCocina");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("OrdenId");

                    b.Property<int>("PlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("PlatoId");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<string>("TerminoCarne")
                        .HasColumnType("text")
                        .HasColumnName("TerminoCarne");

                    b.HasKey("DetalleId")
                        .HasName("PK_DetallesOrden_DetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("PlatoId");

                    b.ToTable("DetallesOrden", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombres");

                    b.Property<string>("PinAcceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PinAcceso");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rol");

                    b.HasKey("EmpleadoId")
                        .HasName("PK_Empleados_EmpleadoId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MesaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MesaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("Capacidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("NumeroMesa");

                    b.HasKey("MesaId")
                        .HasName("PK_Mesas_MesaId");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OrdenId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoId");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaHoraCierre")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaHoraCierre");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaHoraInicio");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("MesaId");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Total");

                    b.HasKey("OrdenId")
                        .HasName("PK_Ordenes_OrdenId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("MesaId");

                    b.ToTable("Ordenes", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Plato", b =>
                {
                    b.Property<int>("PlatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PlatoId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlatoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoriaId");

                    b.Property<int?>("CategoriaPlatoCategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Precio");

                    b.HasKey("PlatoId")
                        .HasName("PK_Platos");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CategoriaPlatoCategoriaId");

                    b.ToTable("Platos", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.TransaccionPago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PagoId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<string>("EstadoIntegracion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EstadoIntegracion");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp")
                        .HasColumnName("FechaPago");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("Monto");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("OrdenId");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text")
                        .HasColumnName("ReferenciaExterna");

                    b.HasKey("PagoId")
                        .HasName("PK_TransaccionesPago_PagoId");

                    b.HasIndex("OrdenId");

                    b.ToTable("TransaccionesPago", (string)null);
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.DetalleOrden", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Entities.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesOrden_Ordenes_OrdenId");

                    b.HasOne("RestaurantePOS.Domain.Entities.Plato", "Plato")
                        .WithMany("DetallesOrden")
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesOrden_Platos_PlatoId");

                    b.Navigation("Orden");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Orden", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Ordenes")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Empleados_EmpleadoId");

                    b.HasOne("RestaurantePOS.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Ordenes")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ordenes_Mesas_MesaId");

                    b.Navigation("Empleado");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Plato", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Entities.CategoriaPlato", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Platos_CategoriasPlato_CategoriaId");

                    b.HasOne("RestaurantePOS.Domain.Entities.CategoriaPlato", null)
                        .WithMany("Platos")
                        .HasForeignKey("CategoriaPlatoCategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.TransaccionPago", b =>
                {
                    b.HasOne("RestaurantePOS.Domain.Entities.Orden", "Orden")
                        .WithMany("Pagos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TransaccionesPago_Ordenes_OrdenId");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.CategoriaPlato", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("RestaurantePOS.Domain.Entities.Plato", b =>
                {
                    b.Navigation("DetallesOrden");
                });
#pragma warning restore 612, 618
        }
    }
}
